version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    command:
      - --innodb-buffer-pool-size=64M
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"